### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Nyholm** [api-php/boilerplate#1]
How should error be handled? 

https://github.com/api-php/boilerplate/blob/master/src/Api/Stats.php#L34

**Comment by sagikazarmark** [comment]
In a well implemented API status codes are used as part of the domain, so I would suggest enforcing domain exceptions here: NotFound, Validation, AccessDenied, etc, whatever makes sense and is provided by the API. Of course we need an UnknownErrorException as well to handle all non-success codes which are not handled by any domain exceptions.

For validation like exceptions I usually also provide a way to get a list of error objects from the exception, so that you can process, fix or do whatever with each error respectively.

**Comment by Nyholm** [comment]
I like this idea. That means we should handle exceptions on all endpoint functions, right?

**Comment by sagikazarmark** [comment]
Yes

**Comment by Nyholm** [comment]
Fixed by #18
