### ISSUE TITLE
Prefer constructor injection, drop lazy initialization

### ISSUE THREAD

**Issue by sagikazarmark** [api-php/boilerplate#3]
I think I already mentioned this somewhere: setter injection and lazy initialization is not really a good idea with the discovery IMO. I think it's better to fail early and know as soon as possible if something is missing. Also, setters doesn't really make sense in most of the cases, as the request builder for example is not used outside of the API context.

**Comment by Nyholm** [comment]
You mentioned that on the Mailgun API. We have adapted =)

The reson I use lazy initialization is for performance. It he RequestBuilder does not need the MultipartStreamBuilder we should not initialize it. Also, if the user has a custom MultipartStreamBuilder we will should not initialize our default first.

Same thing with our discoverable factories. 

I will not lazy load the `RequestBuilder` itself because I assume a `ApiClient` will *always* use it

**Comment by sagikazarmark** [comment]
> Also, if the user has a custom MultipartStreamBuilder we will should not initialize our default first.

Once the request builder is injected into the ApiClient, the RequestBuilder should be immutable. If the user can construct the RequestBuilder with custom parameters then setter injection becomes useless.

As far as I can see there is no way that the request factory is not used, so lazy initialization does not add anything there IMO. Also, lazy initialization is risky when no factories can be found. Failing early is better in this case IMO, as users might get confused if an exception occurs inside the request processing logic because of this.

All that left is performance in case of the multipart stream builder. You can keep the getter there with lazy inizialization since there is no discovery logic there. Setter is not needed if constructor is used.

**Comment by Nyholm** [comment]
> Once the request builder is injected into the ApiClient, the RequestBuilder should be immutable.

I like that idea. It is true for the `RequestBuilder` but not for the `HttpClientConfigurator`.


>  Also, lazy initialization is risky when no factories can be found.  Failing early is better in this case [...]

I agree. That is an issue with the current implementation. 

> All that left is performance in case of the multipart stream builder. You can keep the getter there with lazy inizialization since there is no discovery logic there. Setter is not needed if constructor is used.

Not quite. The [MultipartStreamBuilder does use discovery](https://github.com/php-http/multipart-stream-builder/blob/master/src/MultipartStreamBuilder.php#L43)

One could also argue that the boilerplate (or API clients) should not care much about performance since this is minimal compared to network IO.

**Comment by sagikazarmark** [comment]
> Not quite. The MultipartStreamBuilder does use discovery

Well, then I would vote for removing lazy initialization completely.

> I like that idea. It is true for the RequestBuilder but not for the HttpClientConfigurator.

As I mentioned in another issue, the configurator should not even be a member of the ApiClient. That would solve this issue as well.
